# GitHub Actions Workflow: Deploy Fullstack App to Azure App Service

name: Deploy Fullstack App to Azure Web App - wv-temperature-app-demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install Dependencies for Frontend and Backend
        run: |
          npm install --prefix frontend
          npm install --prefix backend

      - name: Build Frontend
        run: npm run build --prefix frontend

      - name: Prepare Deployment Package
        run: |
          mkdir -p deploy
          cp -r frontend/build deploy/frontend
          cp -r backend deploy/backend
          cp backend/package.json deploy/backend
          cd deploy && zip -r release.zip .
        shell: bash

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: fullstack-app
          path: deploy/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact from Build Job
        uses: actions/download-artifact@v4
        with:
          name: fullstack-app

      - name: Unzip Deployment Package
        run: unzip deploy/release.zip -d deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wv-temperature-app-demo'
          slot-name: 'Production'
          package: ./deploy