name: Build and deploy Node.js app to Azure Web App - wv-temperature-app-demo

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      
      - name: Install root dependencies
        run: |
          pwd
          ls -R
          npm install
          ls -R

      - name: Install Frontend and Backend Dependencies
        run: |
          pwd
          ls -R
          npm install --prefix frontend
          npm install --prefix backend
          ls -R

      - name: Build Frontend
        run: |
          pwd
          ls -R
          npm run build --prefix frontend
          ls -R

      - name: Prepare Deployment Package
        run: |
          pwd
          ls -R
          mkdir -p deploy/frontend deploy/backend
          cp -r frontend/build/* deploy/frontend/
          cp -r backend/* deploy/backend/
          cp backend/package.json deploy/backend/
          ls -R
        shell: bash

      - name: Verify Deployment Package
        # Debugging step to verify contents of deploy directory
        run: |
          echo "Contents of deploy folder:"
          ls -R deploy
        shell: bash

      - name: Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifact
          path: deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment-artifact
      
      - name: List contents of working directory
        run: |
          pwd
          ls -lahR
          mkdir -p deploy
        
      - name: Unzip artifact for deployment
        run: 
          unzip deployment-artifact.zip -d deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'wv-temperature-app-demo'
          package: deploy/frontend
